project_id = "scvdfwpoqutyriinmbbk"

[functions.check-usage-limit]
verify_jwt = false

[functions.convert-document]
verify_jwt = false

[functions.chat-aura]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.admin-dashboard]
verify_jwt = false

[functions.api-status]
verify_jwt = false

[functions.convert-statements-batch]
verify_jwt = false

[functions.razorpay-order]
verify_jwt = false

